# Generated by Django 3.1.3 on 2021-01-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='用户名')),
                ('last_login_ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='上次登录IP')),
                ('last_login_time', models.DateTimeField(auto_now=True, null=True, verbose_name='上次登录时间')),
                ('failNumber', models.IntegerField(default=0, verbose_name='失败次数')),
            ],
            options={
                'verbose_name': '登录信息表',
                'db_table': 'login_info',
            },
        ),
    ]
