def get_role():
    roleObj = {
    'id': 'admin',
    'name': '管理员',
    'describe': '拥有所有权限',
    'status': 1,
    'creatorId': 'system',
    'createTime': 1497160610259,
    'deleted': 0,
    'permissions': [{
      'roleId': 'admin',
      'permissionId': 'dashboard',
      'permissionName': '仪表盘',
      'actions': '[{"action":"add","defaultCheck":False,"describe":"新增"},{"action":"query","defaultCheck":False,"describe":"查询"},{"action":"get","defaultCheck":False,"describe":"详情"},{"action":"update","defaultCheck":False,"describe":"修改"},{"action":"delete","defaultCheck":False,"describe":"删除"}]',
      'actionEntitySet': [{
        'action': 'add',
        'describe': '新增',
        'defaultCheck': False
      }, {
        'action': 'query',
        'describe': '查询',
        'defaultCheck': False
      }, {
        'action': 'get',
        'describe': '详情',
        'defaultCheck': False
      }, {
        'action': 'update',
        'describe': '修改',
        'defaultCheck': False
      }, {
        'action': 'delete',
        'describe': '删除',
        'defaultCheck': False
      }],
      'actionList': None,
      'dataAccess': None
    }, {
      'roleId': 'admin',
      'permissionId': 'exception',
      'permissionName': '异常页面权限',
      'actions': '[{"action":"add","defaultCheck":False,"describe":"新增"},{"action":"query","defaultCheck":False,"describe":"查询"},{"action":"get","defaultCheck":False,"describe":"详情"},{"action":"update","defaultCheck":False,"describe":"修改"},{"action":"delete","defaultCheck":False,"describe":"删除"}]',
      'actionEntitySet': [{
        'action': 'add',
        'describe': '新增',
        'defaultCheck': False
      }, {
        'action': 'query',
        'describe': '查询',
        'defaultCheck': False
      }, {
        'action': 'get',
        'describe': '详情',
        'defaultCheck': False
      }, {
        'action': 'update',
        'describe': '修改',
        'defaultCheck': False
      }, {
        'action': 'delete',
        'describe': '删除',
        'defaultCheck': False
      }],
      'actionList': None,
      'dataAccess': None
    }, {
      'roleId': 'admin',
      'permissionId': 'result',
      'permissionName': '结果权限',
      'actions': '[{"action":"add","defaultCheck":False,"describe":"新增"},{"action":"query","defaultCheck":False,"describe":"查询"},{"action":"get","defaultCheck":False,"describe":"详情"},{"action":"update","defaultCheck":False,"describe":"修改"},{"action":"delete","defaultCheck":False,"describe":"删除"}]',
      'actionEntitySet': [{
        'action': 'add',
        'describe': '新增',
        'defaultCheck': False
      }, {
        'action': 'query',
        'describe': '查询',
        'defaultCheck': False
      }, {
        'action': 'get',
        'describe': '详情',
        'defaultCheck': False
      }, {
        'action': 'update',
        'describe': '修改',
        'defaultCheck': False
      }, {
        'action': 'delete',
        'describe': '删除',
        'defaultCheck': False
      }],
      'actionList': None,
      'dataAccess': None
    }, {
      'roleId': 'admin',
      'permissionId': 'profile',
      'permissionName': '详细页权限',
      'actions': '[{"action":"add","defaultCheck":False,"describe":"新增"},{"action":"query","defaultCheck":False,"describe":"查询"},{"action":"get","defaultCheck":False,"describe":"详情"},{"action":"update","defaultCheck":False,"describe":"修改"},{"action":"delete","defaultCheck":False,"describe":"删除"}]',
      'actionEntitySet': [{
        'action': 'add',
        'describe': '新增',
        'defaultCheck': False
      }, {
        'action': 'query',
        'describe': '查询',
        'defaultCheck': False
      }, {
        'action': 'get',
        'describe': '详情',
        'defaultCheck': False
      }, {
        'action': 'update',
        'describe': '修改',
        'defaultCheck': False
      }, {
        'action': 'delete',
        'describe': '删除',
        'defaultCheck': False
      }],
      'actionList': None,
      'dataAccess': None
    }, {
      'roleId': 'admin',
      'permissionId': 'table',
      'permissionName': '表格权限',
      'actions': '[{"action":"add","defaultCheck":False,"describe":"新增"},{"action":"import","defaultCheck":False,"describe":"导入"},{"action":"get","defaultCheck":False,"describe":"详情"},{"action":"update","defaultCheck":False,"describe":"修改"}]',
      'actionEntitySet': [{
        'action': 'add',
        'describe': '新增',
        'defaultCheck': False
      }, {
        'action': 'import',
        'describe': '导入',
        'defaultCheck': False
      }, {
        'action': 'get',
        'describe': '详情',
        'defaultCheck': False
      }, {
        'action': 'update',
        'describe': '修改',
        'defaultCheck': False
      }],
      'actionList': None,
      'dataAccess': None
    }, {
      'roleId': 'admin',
      'permissionId': 'form',
      'permissionName': '表单权限',
      'actions': '[{"action":"add","defaultCheck":False,"describe":"新增"},{"action":"get","defaultCheck":False,"describe":"详情"},{"action":"query","defaultCheck":False,"describe":"查询"},{"action":"update","defaultCheck":False,"describe":"修改"},{"action":"delete","defaultCheck":False,"describe":"删除"}]',
      'actionEntitySet': [{
        'action': 'add',
        'describe': '新增',
        'defaultCheck': False
      }, {
        'action': 'get',
        'describe': '详情',
        'defaultCheck': False
      }, {
        'action': 'query',
        'describe': '查询',
        'defaultCheck': False
      }, {
        'action': 'update',
        'describe': '修改',
        'defaultCheck': False
      }, {
        'action': 'delete',
        'describe': '删除',
        'defaultCheck': False
      }],
      'actionList': None,
      'dataAccess': None
    }, {
      'roleId': 'admin',
      'permissionId': 'order',
      'permissionName': '订单管理',
      'actions': '[{"action":"add","defaultCheck":False,"describe":"新增"},{"action":"query","defaultCheck":False,"describe":"查询"},{"action":"get","defaultCheck":False,"describe":"详情"},{"action":"update","defaultCheck":False,"describe":"修改"},{"action":"delete","defaultCheck":False,"describe":"删除"}]',
      'actionEntitySet': [{
        'action': 'add',
        'describe': '新增',
        'defaultCheck': False
      }, {
        'action': 'query',
        'describe': '查询',
        'defaultCheck': False
      }, {
        'action': 'get',
        'describe': '详情',
        'defaultCheck': False
      }, {
        'action': 'update',
        'describe': '修改',
        'defaultCheck': False
      }, {
        'action': 'delete',
        'describe': '删除',
        'defaultCheck': False
      }],
      'actionList': None,
      'dataAccess': None
    }, {
      'roleId': 'admin',
      'permissionId': 'permission',
      'permissionName': '权限管理',
      'actions': '[{"action":"add","defaultCheck":False,"describe":"新增"},{"action":"get","defaultCheck":False,"describe":"详情"},{"action":"update","defaultCheck":False,"describe":"修改"},{"action":"delete","defaultCheck":False,"describe":"删除"}]',
      'actionEntitySet': [{
        'action': 'add',
        'describe': '新增',
        'defaultCheck': False
      }, {
        'action': 'get',
        'describe': '详情',
        'defaultCheck': False
      }, {
        'action': 'update',
        'describe': '修改',
        'defaultCheck': False
      }, {
        'action': 'delete',
        'describe': '删除',
        'defaultCheck': False
      }],
      'actionList': None,
      'dataAccess': None
    }, {
      'roleId': 'admin',
      'permissionId': 'role',
      'permissionName': '角色管理',
      'actions': '[{"action":"add","defaultCheck":False,"describe":"新增"},{"action":"get","defaultCheck":False,"describe":"详情"},{"action":"update","defaultCheck":False,"describe":"修改"},{"action":"delete","defaultCheck":False,"describe":"删除"}]',
      'actionEntitySet': [{
        'action': 'add',
        'describe': '新增',
        'defaultCheck': False
      }, {
        'action': 'get',
        'describe': '详情',
        'defaultCheck': False
      }, {
        'action': 'update',
        'describe': '修改',
        'defaultCheck': False
      }, {
        'action': 'delete',
        'describe': '删除',
        'defaultCheck': False
      }],
      'actionList': None,
      'dataAccess': None
    }, {
      'roleId': 'admin',
      'permissionId': 'table',
      'permissionName': '桌子管理',
      'actions': '[{"action":"add","defaultCheck":False,"describe":"新增"},{"action":"get","defaultCheck":False,"describe":"详情"},{"action":"query","defaultCheck":False,"describe":"查询"},{"action":"update","defaultCheck":False,"describe":"修改"},{"action":"delete","defaultCheck":False,"describe":"删除"}]',
      'actionEntitySet': [{
        'action': 'add',
        'describe': '新增',
        'defaultCheck': False
      }, {
        'action': 'get',
        'describe': '详情',
        'defaultCheck': False
      }, {
        'action': 'query',
        'describe': '查询',
        'defaultCheck': False
      }, {
        'action': 'update',
        'describe': '修改',
        'defaultCheck': False
      }, {
        'action': 'delete',
        'describe': '删除',
        'defaultCheck': False
      }],
      'actionList': None,
      'dataAccess': None
    }, {
      'roleId': 'admin',
      'permissionId': 'user',
      'permissionName': '用户管理',
      'actions': '[{"action":"add","defaultCheck":False,"describe":"新增"},{"action":"import","defaultCheck":False,"describe":"导入"},{"action":"get","defaultCheck":False,"describe":"详情"},{"action":"update","defaultCheck":False,"describe":"修改"},{"action":"delete","defaultCheck":False,"describe":"删除"},{"action":"export","defaultCheck":False,"describe":"导出"}]',
      'actionEntitySet': [{
        'action': 'add',
        'describe': '新增',
        'defaultCheck': False
      }, {
        'action': 'import',
        'describe': '导入',
        'defaultCheck': False
      }, {
        'action': 'get',
        'describe': '详情',
        'defaultCheck': False
      }, {
        'action': 'update',
        'describe': '修改',
        'defaultCheck': False
      }, {
        'action': 'delete',
        'describe': '删除',
        'defaultCheck': False
      }, {
        'action': 'export',
        'describe': '导出',
        'defaultCheck': False
      }],
      'actionList': None,
      'dataAccess': None
    }]
    }

    roleObj['permissions'].append({
    'roleId': 'admin',
    'permissionId': 'support',
    'permissionName': '超级模块',
    'actions': '[{"action":"add","defaultCheck":False,"describe":"新增"},{"action":"import","defaultCheck":False,"describe":"导入"},{"action":"get","defaultCheck":False,"describe":"详情"},{"action":"update","defaultCheck":False,"describe":"修改"},{"action":"delete","defaultCheck":False,"describe":"删除"},{"action":"export","defaultCheck":False,"describe":"导出"}]',
    'actionEntitySet': [{
      'action': 'add',
      'describe': '新增',
      'defaultCheck': False
    }, {
      'action': 'import',
      'describe': '导入',
      'defaultCheck': False
    }, {
      'action': 'get',
      'describe': '详情',
      'defaultCheck': False
    }, {
      'action': 'update',
      'describe': '修改',
      'defaultCheck': False
    }, {
      'action': 'delete',
      'describe': '删除',
      'defaultCheck': False
    }, {
      'action': 'export',
      'describe': '导出',
      'defaultCheck': False
    }],
    'actionList': None,
    'dataAccess': None
    })
    return roleObj

def user_info():
    userinfo = {
    'id': '4291d7da9005377ec9aec4a71ea837f',
    'name': '超级管理员',
    'username': 'admin',
    # 'password': '',
    # 'avatar': '/avatar1.jpg',
    # 'status': 1,
    # 'telephone': '',
    # 'lastLoginIp': '27.154.74.117',
    # 'lastLoginTime': 1534837621348,
    # 'creatorId': 'admin',
    # 'createTime': 1497160610259,
    # 'merchantCode': 'TLif2btpzg079h15bk',
    # 'deleted': 0,
    # 'roleId': 'admin',
    'role': get_role()
    }
    return userinfo