# Generated by Django 3.1.3 on 2021-01-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZYImportData',
            fields=[
                ('id', models.IntegerField(blank=True, help_text='id', primary_key=True, serialize=False)),
                ('no', models.CharField(blank=True, help_text='no', max_length=32, null=True)),
                ('datetime', models.DateTimeField(blank=True, help_text='时间', null=True)),
                ('business_manager', models.CharField(blank=True, help_text='业务员', max_length=32, null=True)),
                ('source', models.CharField(blank=True, help_text='来源', max_length=32, null=True)),
                ('currency', models.CharField(blank=True, help_text='币种', max_length=16, null=True)),
                ('price', models.FloatField(blank=True, help_text='金额', null=True)),
                ('cost', models.FloatField(blank=True, help_text='成本', null=True)),
                ('refund', models.FloatField(blank=True, help_text='费用', null=True)),
                ('income', models.FloatField(blank=True, help_text='人民币收入', null=True)),
                ('purchasing_cost', models.FloatField(blank=True, help_text='采购成本', null=True)),
                ('profit', models.FloatField(blank=True, help_text='利润', null=True)),
                ('product_id', models.CharField(blank=True, help_text='产品ID', max_length=32, null=True)),
                ('asin', models.CharField(blank=True, help_text='ASIN', max_length=32, null=True)),
                ('sku', models.CharField(blank=True, help_text='SKU', max_length=64, null=True)),
                ('zh_name', models.CharField(blank=True, help_text='中文简称', max_length=64, null=True)),
                ('gross_weight', models.IntegerField(blank=True, help_text='毛重', null=True)),
                ('size', models.CharField(blank=True, help_text='尺寸', max_length=16, null=True)),
                ('quantity', models.IntegerField(blank=True, help_text='数量', null=True)),
                ('logistics', models.CharField(blank=True, help_text='物流', max_length=16, null=True)),
                ('channel', models.CharField(blank=True, help_text='渠道', max_length=64, null=True)),
                ('waybill_no', models.CharField(blank=True, help_text='运单号', max_length=64, null=True)),
                ('track_no', models.CharField(blank=True, help_text='追踪号', max_length=64, null=True)),
                ('freight', models.FloatField(blank=True, help_text='运费', null=True)),
                ('order_remarks', models.TextField(blank=True, help_text='订单备注', null=True)),
                ('region', models.CharField(blank=True, help_text='地区', max_length=10, null=True)),
                ('buyer', models.CharField(blank=True, help_text='买家名称', max_length=128, null=True)),
                ('mailbox', models.CharField(blank=True, help_text='邮箱', max_length=128, null=True)),
                ('telephone', models.CharField(blank=True, help_text='电话', max_length=64, null=True)),
                ('city', models.CharField(blank=True, help_text='城市', max_length=32, null=True)),
                ('state', models.CharField(blank=True, help_text='州省', max_length=32, null=True)),
                ('postcode', models.CharField(blank=True, help_text='邮编', max_length=16, null=True)),
                ('address', models.TextField(blank=True, help_text='地址', null=True)),
            ],
            options={
                'verbose_name': '智盈导入数据',
                'db_table': 'zy_import_data',
            },
        ),
    ]
